home:
    path:      /
    methods: [GET]
    defaults:  { _controller: NecryinCCBundle:Main:index }

api_convert:
    path:      /convert/currency.{_format}
    methods: [GET]
    defaults:  { _format: json, _controller: NecryinCCBundle:Api:convert }

api_get_rates:
    path:      /{provider}/rates.{_format}
    methods: [GET]
    defaults:  { _format: json, _controller: NecryinCCBundle:Api:getRates, providerAlias: cb }

api_get_providers_aliases:
    path:      /providers.{_format}
    methods: [GET]
    defaults:  { _format: json, _controller: NecryinCCBundle:Api:getProvidersAliases }
