parameters:
    exchange_provider.cb: cb
    exchange_provider.openexchange: openexchange

services:

    necryin_cc.abstract_exchange_provider:
        abstract: true
        class: Necryin\CCBundle\Provider\AbstractExchangeProvider
        calls:
            - [setClient, [@guzzle.client]]

    necryin_cc.cb_exchange_provider:
        class: Necryin\CCBundle\Provider\CbExchangeProvider
        parent: necryin_cc.abstract_exchange_provider
        tags:
            - { name: necryin.exchange_provider, alias: '%exchange_provider.cb%' }

    necryin.openexchange_exchange_provider:
        class: Necryin\CCBundle\Provider\OpenexchangeExchangeProvider
        parent: necryin_cc.abstract_exchange_provider
        calls:
            - [setAppId, ['%openexchange.app_id%']]
        tags:
            - { name: necryin.exchange_provider, alias: '%exchange_provider.openexchange%' }

    necryin.exchange_provider_manager:
        class: Necryin\CCBundle\Manager\ExchangeProviderManager
        arguments: [@service_container]

    necryin.currency_converter_service:
        class: Necryin\CCBundle\Service\CurrencyConverterService
        arguments: [@necryin.exchange_provider_manager, @cache]
