services:
    necryin_cc.stub_exchange_provider:
        class: Necryin\CCBundle\Provider\StubExchangeProvider
        arguments: [@guzzle.client]
        tags:
            - { name: necryin.exchange_provider, alias: 'stub' }
