services:
    necryin_cc.currency_converter:
        class: Necryin\CCBundle\Request\ParamConverter\CurrencyConverter
        tags:
            - { name: request.param_converter, priority: 1, converter: currency_converter }

    necryin_cc.cb_exchange_provider:
        class: Necryin\CCBundle\Provider\CbExchangeProvider
        arguments: [@guzzle.client, @necryin_cc.currency_manager]
        tags:
            - { name: necryin.exchange_provider, alias: cb }

    necryin_cc.currency_manager:
        class: Necryin\CCBundle\Model\CurrencyManager

    necryin.exchange_provider_factory:
        class: Necryin\CCBundle\Factory\ExchangeProviderFactory

    necryin.openexchange_exchange_provider:
        class: Necryin\CCBundle\Provider\OpenexchangeExchangeProvider
        arguments: [@guzzle.client, @necryin_cc.currency_manager, '%openexchange.app_id%']
        tags:
            - { name: necryin.exchange_provider, alias: openexchange }

    necryin.calculate_currency_service:
        class: Necryin\CCBundle\Service\CalculateCurrencyService
        arguments: [@necryin.exchange_provider_factory]
